name: OnePunchSurvival
version: 0.1
main: tk.pshub.parangee.onepunchsurvival.plugin.OnePunchSurvival
authors: [parangee]
depend:
  - Kotlin
  - Tap
commands:
  onepunch:
    permission: onepunch-command